// This file was auto-generated by Fern from our API Definition.

package client

import (
	apigateways "go-mod-path/generated/go/apigateways"
	core "go-mod-path/generated/go/core"
	option "go-mod-path/generated/go/option"
	routes "go-mod-path/generated/go/routes"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header

	Apigateways *apigateways.Client
	Routes      *routes.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: core.NewCaller(
			&core.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:      options.ToHeader(),
		Apigateways: apigateways.NewClient(opts...),
		Routes:      routes.NewClient(opts...),
	}
}
