// This file was auto-generated by Fern from our API Definition.

package api

import (
	fmt "fmt"
)

type ApigatewaysGetRequest struct {
	// The first element (of the total list of elements) to include in the response. Use together with limit for pagination.
	Offset *int `json:"-" url:"offset,omitempty"`
	// The maximum number of elements to return. Use together with offset for pagination.
	Limit *int `json:"-" url:"limit,omitempty"`
	// The field to order the results by. If not provided, the results will be ordered by the default field.
	OrderBy *ApigatewaysGetRequestOrderBy `json:"-" url:"orderBy,omitempty"`
}

type GatewayCreate struct {
	// Metadata
	Metadata   map[string]interface{} `json:"metadata,omitempty" url:"-"`
	Properties *Gateway               `json:"properties,omitempty" url:"-"`
}

type GatewayEnsure struct {
	// The ID (UUID) of the Gateway.
	Id *string `json:"id,omitempty" url:"-"`
	// Metadata
	Metadata   map[string]interface{} `json:"metadata,omitempty" url:"-"`
	Properties *Gateway               `json:"properties,omitempty" url:"-"`
}

type ApigatewaysGetRequestOrderBy string

const (
	ApigatewaysGetRequestOrderByCreatedDate      ApigatewaysGetRequestOrderBy = "-createdDate"
	ApigatewaysGetRequestOrderByLastModifiedDate ApigatewaysGetRequestOrderBy = "-lastModifiedDate"
	ApigatewaysGetRequestOrderByName             ApigatewaysGetRequestOrderBy = "-name"
)

func NewApigatewaysGetRequestOrderByFromString(s string) (ApigatewaysGetRequestOrderBy, error) {
	switch s {
	case "-createdDate":
		return ApigatewaysGetRequestOrderByCreatedDate, nil
	case "-lastModifiedDate":
		return ApigatewaysGetRequestOrderByLastModifiedDate, nil
	case "-name":
		return ApigatewaysGetRequestOrderByName, nil
	}
	var t ApigatewaysGetRequestOrderBy
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a ApigatewaysGetRequestOrderBy) Ptr() *ApigatewaysGetRequestOrderBy {
	return &a
}
