// This file was auto-generated by Fern from our API Definition.

package api

import (
	fmt "fmt"
)

type ApigatewaysRoutesGetRequest struct {
	// The first element (of the total list of elements) to include in the response. Use together with limit for pagination.
	Offset *int `json:"-" url:"offset,omitempty"`
	// The maximum number of elements to return. Use together with offset for pagination.
	Limit *int `json:"-" url:"limit,omitempty"`
	// The field to order the results by. If not provided, the results will be ordered by the default field.
	OrderBy *ApigatewaysRoutesGetRequestOrderBy `json:"-" url:"orderBy,omitempty"`
}

type RouteCreate struct {
	// Metadata
	Metadata   map[string]interface{} `json:"metadata,omitempty" url:"-"`
	Properties *Route                 `json:"properties,omitempty" url:"-"`
}

type RouteEnsure struct {
	// The ID (UUID) of the Route.
	Id *string `json:"id,omitempty" url:"-"`
	// Metadata
	Metadata   map[string]interface{} `json:"metadata,omitempty" url:"-"`
	Properties *Route                 `json:"properties,omitempty" url:"-"`
}

type ApigatewaysRoutesGetRequestOrderBy string

const (
	ApigatewaysRoutesGetRequestOrderByCreatedDate      ApigatewaysRoutesGetRequestOrderBy = "-createdDate"
	ApigatewaysRoutesGetRequestOrderByLastModifiedDate ApigatewaysRoutesGetRequestOrderBy = "-lastModifiedDate"
	ApigatewaysRoutesGetRequestOrderByName             ApigatewaysRoutesGetRequestOrderBy = "-name"
)

func NewApigatewaysRoutesGetRequestOrderByFromString(s string) (ApigatewaysRoutesGetRequestOrderBy, error) {
	switch s {
	case "-createdDate":
		return ApigatewaysRoutesGetRequestOrderByCreatedDate, nil
	case "-lastModifiedDate":
		return ApigatewaysRoutesGetRequestOrderByLastModifiedDate, nil
	case "-name":
		return ApigatewaysRoutesGetRequestOrderByName, nil
	}
	var t ApigatewaysRoutesGetRequestOrderBy
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a ApigatewaysRoutesGetRequestOrderBy) Ptr() *ApigatewaysRoutesGetRequestOrderBy {
	return &a
}
