// This file was auto-generated by Fern from our API Definition.

// An API gateway consists of the generic rules and configurations of an API Gateway.
// 
// This tag groups all operations for apigateways.
// 
package apigateways
