// This file was auto-generated by Fern from our API Definition.

// A route is a rule that maps an incoming request to a specific backend service.
// 
// This tag groups all operations for routes.
// 
package routes
